# Default configuration for solr_wrapper in development environment
instance_dir: tmp/solr-development
port: 8983
collection:
  persist: true
  # dir: .internal_test_app/solr/config/
  name: hydra-development
