# Default configuration for solr_wrapper in development environment
version: 6.6.1
instance_dir: tmp/solr-development
port: 8983
verbose: true
collection:
  persist: true
  dir: .internal_test_app/solr/config/
  name: hydra-development
